theme = "solarized_dark"

[editor]
line-number = "relative"
mouse = false
auto-pairs = false
rulers = [100]

[keys.normal]
"C-s" = "split_selection_on_newline"
# "C-l" = "increment"
# "C-h" = "decrement"
"C-r" = "redo"

# Some nice Helix stuff
C-h = "shrink_selection"
C-l = "expand_selection"
C-k = "select_prev_sibling"
C-j = "select_next_sibling"

C-l = "select_next_sibling"
D = "kill_to_line_end"
H = "goto_first_nonwhitespace"
L = "goto_line_end"
G = "goto_file_end"
P = ["paste_clipboard_before", "collapse_selection"]
V = ["select_mode", "extend_to_line_bounds"]
"space" = { "tab" = ":buffer-previous" }

a = ["append_mode", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
x = ["extend_line_below", "select_mode"]

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]

[keys.insert]
# Map `jk` to go back to normal mode
j = { k = "normal_mode" }

[keys.select]
# Map `jk` to go back to normal mode
j = { k = "normal_mode" }

"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%" = "match_brackets"
S = "surround_add" # Basically 99% of what I use vim-surround for

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]

# Clipboards over registers ye ye
d = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = ["replace_selections_with_clipboard", "normal_mode", "collapse_selection"] # No life without this
P = "paste_clipboard_before"

# Escape the madness! No more fighting with the cursor! Or with multiple cursors!
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
